TRUNCATE TABLE tit;
COPY tit 
(
   nriga ,
   c_codiceamministrativo , 
   c_sezione , 
   s_identificativosoggetto , 
   s_tiposoggetto ,
   i_identificativoimmobile ,
   i_tipoimmobile ,
   t_codicediritto ,
   t_titolononcodificato ,
   t_quotanumeratore ,
   t_quotadenominatore ,
   t_regime ,
   t_soggettodiriferimento ,
   ag_datavalidita ,
   ag_tiponota ,
   ag_numeronota ,
   ag_progressivonota ,
   ag_annonota ,
   ag_datadiregitrazioneinatti ,
   ag_partita ,
   ac_datavalidita ,
   ac_tiponota ,
   ac_numeronota ,
   ac_progressivonota ,
   ac_annonota ,
   ac_datadiregitrazioneinatti ,
   idmutazioneiniziale ,
   idmutazionefinale ,
   idtitolarita ,
   ag_codicecausaleattogen ,
   ag_descrizioneattogen ,
   ac_codicecausaleattoconc ,
   ac_descrizioneattoconc 
   )
from 'C:/vilcatasto/fabi.TIT' WITH CSV DELIMITER '|' ESCAPE E'\\'QUOTE '#';
COPY tit
(
   nriga ,
   c_codiceamministrativo , 
   c_sezione , 
   s_identificativosoggetto , 
   s_tiposoggetto ,
   i_identificativoimmobile ,
   i_tipoimmobile ,
   t_codicediritto ,
   t_titolononcodificato ,
   t_quotanumeratore ,
   t_quotadenominatore ,
   t_regime ,
   t_soggettodiriferimento ,
   ag_datavalidita ,
   ag_tiponota ,
   ag_numeronota ,
   ag_progressivonota ,
   ag_annonota ,
   ag_datadiregitrazioneinatti ,
   ag_partita ,
   ac_datavalidita ,
   ac_tiponota ,
   ac_numeronota ,
   ac_progressivonota ,
   ac_annonota ,
   ac_datadiregitrazioneinatti ,
   idmutazioneiniziale ,
   idmutazionefinale ,
   idtitolarita ,
   ag_codicecausaleattogen ,
   ag_descrizioneattogen ,
   ac_codicecausaleattoconc ,
   ac_descrizioneattoconc 
   )
from 'C:/vilcatasto/teri.TIT' WITH CSV DELIMITER '|' ESCAPE E'\\' QUOTE '#';
